/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CollaborationRating = IDL.Record({
  'communication' : IDL.Nat8,
  'reliability' : IDL.Nat8,
  'skillAccuracy' : IDL.Nat8,
  'reviewer' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const SkillLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'expert' : IDL.Null,
});
export const ProjectRole = IDL.Record({
  'experienceLevel' : SkillLevel,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const ProjectCategory = IDL.Variant({
  'movie' : IDL.Null,
  'album' : IDL.Null,
  'other' : IDL.Text,
  'game' : IDL.Null,
  'comic' : IDL.Null,
  'musicVideo' : IDL.Null,
  'shortFilm' : IDL.Null,
  'novel' : IDL.Null,
});
export const ProjectPosting = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'externalLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'vibes' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'goals' : IDL.Vec(IDL.Text),
  'rolesNeeded' : IDL.Vec(ProjectRole),
  'genres' : IDL.Vec(IDL.Text),
  'category' : ProjectCategory,
  'timeline' : IDL.Int,
});
export const CreativeProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'skillTags' : IDL.Vec(IDL.Text),
  'lookingFor' : IDL.Text,
  'availability' : IDL.Text,
  'updatedAt' : Time,
  'moodTags' : IDL.Vec(IDL.Text),
  'goals' : IDL.Vec(IDL.Text),
  'genres' : IDL.Vec(IDL.Text),
  'skillLevel' : SkillLevel,
  'portfolioLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'inspirations' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCollaborationRating' : IDL.Func(
      [IDL.Principal, IDL.Nat, CollaborationRating],
      [],
      [],
    ),
  'addMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addProjectCollaborator' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'addTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([ProjectPosting], [IDL.Nat], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(ProjectPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CreativeProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollaborationRatings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CollaborationRating)],
      ['query'],
    ),
  'getCreativeProfile' : IDL.Func(
      [IDL.Principal],
      [CreativeProfile],
      ['query'],
    ),
  'getFilteredProjectsByGenre' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(ProjectPosting)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, Time))],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Nat], [ProjectPosting], ['query']),
  'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CreativeProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markProjectCompleted' : IDL.Func([IDL.Nat], [], []),
  'removeProjectCollaborator' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([CreativeProfile], [], []),
  'saveOrUpdateCreativeProfile' : IDL.Func([CreativeProfile], [], []),
  'updateProject' : IDL.Func([IDL.Nat, ProjectPosting], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CollaborationRating = IDL.Record({
    'communication' : IDL.Nat8,
    'reliability' : IDL.Nat8,
    'skillAccuracy' : IDL.Nat8,
    'reviewer' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const SkillLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'expert' : IDL.Null,
  });
  const ProjectRole = IDL.Record({
    'experienceLevel' : SkillLevel,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const ProjectCategory = IDL.Variant({
    'movie' : IDL.Null,
    'album' : IDL.Null,
    'other' : IDL.Text,
    'game' : IDL.Null,
    'comic' : IDL.Null,
    'musicVideo' : IDL.Null,
    'shortFilm' : IDL.Null,
    'novel' : IDL.Null,
  });
  const ProjectPosting = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'externalLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'vibes' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'goals' : IDL.Vec(IDL.Text),
    'rolesNeeded' : IDL.Vec(ProjectRole),
    'genres' : IDL.Vec(IDL.Text),
    'category' : ProjectCategory,
    'timeline' : IDL.Int,
  });
  const CreativeProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'skillTags' : IDL.Vec(IDL.Text),
    'lookingFor' : IDL.Text,
    'availability' : IDL.Text,
    'updatedAt' : Time,
    'moodTags' : IDL.Vec(IDL.Text),
    'goals' : IDL.Vec(IDL.Text),
    'genres' : IDL.Vec(IDL.Text),
    'skillLevel' : SkillLevel,
    'portfolioLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'inspirations' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCollaborationRating' : IDL.Func(
        [IDL.Principal, IDL.Nat, CollaborationRating],
        [],
        [],
      ),
    'addMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addProjectCollaborator' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'addTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([ProjectPosting], [IDL.Nat], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(ProjectPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CreativeProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollaborationRatings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CollaborationRating)],
        ['query'],
      ),
    'getCreativeProfile' : IDL.Func(
        [IDL.Principal],
        [CreativeProfile],
        ['query'],
      ),
    'getFilteredProjectsByGenre' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(ProjectPosting)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, Time))],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [ProjectPosting], ['query']),
    'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CreativeProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markProjectCompleted' : IDL.Func([IDL.Nat], [], []),
    'removeProjectCollaborator' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([CreativeProfile], [], []),
    'saveOrUpdateCreativeProfile' : IDL.Func([CreativeProfile], [], []),
    'updateProject' : IDL.Func([IDL.Nat, ProjectPosting], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };