/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CollaborationRating {
  'communication' : number,
  'reliability' : number,
  'skillAccuracy' : number,
  'reviewer' : Principal,
}
export interface CreativeProfile {
  'bio' : string,
  'displayName' : string,
  'createdAt' : Time,
  'skillTags' : Array<string>,
  'lookingFor' : string,
  'availability' : string,
  'updatedAt' : Time,
  'moodTags' : Array<string>,
  'goals' : Array<string>,
  'genres' : Array<string>,
  'skillLevel' : SkillLevel,
  'portfolioLinks' : Array<[string, string]>,
  'inspirations' : Array<string>,
}
export type ProjectCategory = { 'movie' : null } |
  { 'album' : null } |
  { 'other' : string } |
  { 'game' : null } |
  { 'comic' : null } |
  { 'musicVideo' : null } |
  { 'shortFilm' : null } |
  { 'novel' : null };
export interface ProjectPosting {
  'id' : bigint,
  'status' : ProjectStatus,
  'title' : string,
  'creator' : Principal,
  'externalLinks' : Array<[string, string]>,
  'vibes' : Array<string>,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'goals' : Array<string>,
  'rolesNeeded' : Array<ProjectRole>,
  'genres' : Array<string>,
  'category' : ProjectCategory,
  'timeline' : bigint,
}
export interface ProjectRole {
  'experienceLevel' : SkillLevel,
  'name' : string,
  'description' : string,
  'requiredSkills' : Array<string>,
}
export type ProjectStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type SkillLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'expert' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCollaborationRating' : ActorMethod<
    [Principal, bigint, CollaborationRating],
    undefined
  >,
  'addMessage' : ActorMethod<[bigint, string], undefined>,
  'addProjectCollaborator' : ActorMethod<[bigint, Principal], undefined>,
  'addTask' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[ProjectPosting], bigint>,
  'getAllProjects' : ActorMethod<[], Array<ProjectPosting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CreativeProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollaborationRatings' : ActorMethod<
    [Principal],
    Array<CollaborationRating>
  >,
  'getCreativeProfile' : ActorMethod<[Principal], CreativeProfile>,
  'getFilteredProjectsByGenre' : ActorMethod<
    [Array<string>],
    Array<ProjectPosting>
  >,
  'getMessages' : ActorMethod<[bigint], Array<[Principal, string, Time]>>,
  'getProject' : ActorMethod<[bigint], ProjectPosting>,
  'getTasks' : ActorMethod<[bigint], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CreativeProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markProjectCompleted' : ActorMethod<[bigint], undefined>,
  'removeProjectCollaborator' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[CreativeProfile], undefined>,
  'saveOrUpdateCreativeProfile' : ActorMethod<[CreativeProfile], undefined>,
  'updateProject' : ActorMethod<[bigint, ProjectPosting], undefined>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];