/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProjectRole {
    experienceLevel: SkillLevel;
    name: string;
    description: string;
    requiredSkills: Array<string>;
}
export type Time = bigint;
export interface CreativeProfile {
    bio: string;
    displayName: string;
    createdAt: Time;
    skillTags: Array<string>;
    lookingFor: string;
    availability: string;
    updatedAt: Time;
    moodTags: Array<string>;
    goals: Array<string>;
    genres: Array<string>;
    skillLevel: SkillLevel;
    portfolioLinks: Array<[string, string]>;
    inspirations: Array<string>;
}
export interface CollaborationRating {
    communication: number;
    reliability: number;
    skillAccuracy: number;
    reviewer: Principal;
}
export type ProjectCategory = {
    __kind__: "movie";
    movie: null;
} | {
    __kind__: "album";
    album: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "game";
    game: null;
} | {
    __kind__: "comic";
    comic: null;
} | {
    __kind__: "musicVideo";
    musicVideo: null;
} | {
    __kind__: "shortFilm";
    shortFilm: null;
} | {
    __kind__: "novel";
    novel: null;
};
export interface ProjectPosting {
    id: bigint;
    status: ProjectStatus;
    title: string;
    creator: Principal;
    externalLinks: Array<[string, string]>;
    vibes: Array<string>;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    goals: Array<string>;
    rolesNeeded: Array<ProjectRole>;
    genres: Array<string>;
    category: ProjectCategory;
    timeline: bigint;
}
export enum ProjectStatus {
    cancelled = "cancelled",
    open = "open",
    completed = "completed",
    inProgress = "inProgress"
}
export enum SkillLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    expert = "expert"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCollaborationRating(targetUser: Principal, projectId: bigint, rating: CollaborationRating): Promise<void>;
    addMessage(projectId: bigint, message: string): Promise<void>;
    addProjectCollaborator(projectId: bigint, collaborator: Principal): Promise<void>;
    addTask(projectId: bigint, task: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(project: ProjectPosting): Promise<bigint>;
    getAllProjects(): Promise<Array<ProjectPosting>>;
    getCallerUserProfile(): Promise<CreativeProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollaborationRatings(user: Principal): Promise<Array<CollaborationRating>>;
    getCreativeProfile(user: Principal): Promise<CreativeProfile>;
    getFilteredProjectsByGenre(desiredGenres: Array<string>): Promise<Array<ProjectPosting>>;
    getMessages(projectId: bigint): Promise<Array<[Principal, string, Time]>>;
    getProject(projectId: bigint): Promise<ProjectPosting>;
    getTasks(projectId: bigint): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<CreativeProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markProjectCompleted(projectId: bigint): Promise<void>;
    removeProjectCollaborator(projectId: bigint, collaborator: Principal): Promise<void>;
    saveCallerUserProfile(profile: CreativeProfile): Promise<void>;
    saveOrUpdateCreativeProfile(profile: CreativeProfile): Promise<void>;
    updateProject(projectId: bigint, updatedProject: ProjectPosting): Promise<void>;
    updateUserRole(user: Principal, role: UserRole): Promise<void>;
}
import type { CreativeProfile as _CreativeProfile, ProjectCategory as _ProjectCategory, ProjectPosting as _ProjectPosting, ProjectRole as _ProjectRole, ProjectStatus as _ProjectStatus, SkillLevel as _SkillLevel, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCollaborationRating(arg0: Principal, arg1: bigint, arg2: CollaborationRating): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollaborationRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollaborationRating(arg0, arg1, arg2);
            return result;
        }
    }
    async addMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1);
            return result;
        }
    }
    async addProjectCollaborator(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectCollaborator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectCollaborator(arg0, arg1);
            return result;
        }
    }
    async addTask(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: ProjectPosting): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_ProjectPosting_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_ProjectPosting_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllProjects(): Promise<Array<ProjectPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<CreativeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollaborationRatings(arg0: Principal): Promise<Array<CollaborationRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollaborationRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollaborationRatings(arg0);
            return result;
        }
    }
    async getCreativeProfile(arg0: Principal): Promise<CreativeProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreativeProfile(arg0);
                return from_candid_CreativeProfile_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreativeProfile(arg0);
            return from_candid_CreativeProfile_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredProjectsByGenre(arg0: Array<string>): Promise<Array<ProjectPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredProjectsByGenre(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredProjectsByGenre(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<[Principal, string, Time]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<ProjectPosting> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_ProjectPosting_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_ProjectPosting_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<CreativeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markProjectCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markProjectCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markProjectCompleted(arg0);
            return result;
        }
    }
    async removeProjectCollaborator(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProjectCollaborator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProjectCollaborator(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: CreativeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_CreativeProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_CreativeProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveOrUpdateCreativeProfile(arg0: CreativeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOrUpdateCreativeProfile(to_candid_CreativeProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOrUpdateCreativeProfile(to_candid_CreativeProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: ProjectPosting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_ProjectPosting_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_ProjectPosting_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CreativeProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreativeProfile): CreativeProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectCategory): ProjectCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectPosting_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPosting): ProjectPosting {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectRole): ProjectRole {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SkillLevel_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillLevel): SkillLevel {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CreativeProfile]): CreativeProfile | null {
    return value.length === 0 ? null : from_candid_CreativeProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    title: string;
    creator: Principal;
    externalLinks: Array<[string, string]>;
    vibes: Array<string>;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    goals: Array<string>;
    rolesNeeded: Array<_ProjectRole>;
    genres: Array<string>;
    category: _ProjectCategory;
    timeline: bigint;
}): {
    id: bigint;
    status: ProjectStatus;
    title: string;
    creator: Principal;
    externalLinks: Array<[string, string]>;
    vibes: Array<string>;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    goals: Array<string>;
    rolesNeeded: Array<ProjectRole>;
    genres: Array<string>;
    category: ProjectCategory;
    timeline: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        creator: value.creator,
        externalLinks: value.externalLinks,
        vibes: value.vibes,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        goals: value.goals,
        rolesNeeded: from_candid_vec_n19(_uploadFile, _downloadFile, value.rolesNeeded),
        genres: value.genres,
        category: from_candid_ProjectCategory_n24(_uploadFile, _downloadFile, value.category),
        timeline: value.timeline
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: _SkillLevel;
    name: string;
    description: string;
    requiredSkills: Array<string>;
}): {
    experienceLevel: SkillLevel;
    name: string;
    description: string;
    requiredSkills: Array<string>;
} {
    return {
        experienceLevel: from_candid_SkillLevel_n22(_uploadFile, _downloadFile, value.experienceLevel),
        name: value.name,
        description: value.description,
        requiredSkills: value.requiredSkills
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    createdAt: _Time;
    skillTags: Array<string>;
    lookingFor: string;
    availability: string;
    updatedAt: _Time;
    moodTags: Array<string>;
    goals: Array<string>;
    genres: Array<string>;
    skillLevel: _SkillLevel;
    portfolioLinks: Array<[string, string]>;
    inspirations: Array<string>;
}): {
    bio: string;
    displayName: string;
    createdAt: Time;
    skillTags: Array<string>;
    lookingFor: string;
    availability: string;
    updatedAt: Time;
    moodTags: Array<string>;
    goals: Array<string>;
    genres: Array<string>;
    skillLevel: SkillLevel;
    portfolioLinks: Array<[string, string]>;
    inspirations: Array<string>;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        createdAt: value.createdAt,
        skillTags: value.skillTags,
        lookingFor: value.lookingFor,
        availability: value.availability,
        updatedAt: value.updatedAt,
        moodTags: value.moodTags,
        goals: value.goals,
        genres: value.genres,
        skillLevel: from_candid_SkillLevel_n22(_uploadFile, _downloadFile, value.skillLevel),
        portfolioLinks: value.portfolioLinks,
        inspirations: value.inspirations
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): ProjectStatus {
    return "cancelled" in value ? ProjectStatus.cancelled : "open" in value ? ProjectStatus.open : "completed" in value ? ProjectStatus.completed : "inProgress" in value ? ProjectStatus.inProgress : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
}): SkillLevel {
    return "intermediate" in value ? SkillLevel.intermediate : "beginner" in value ? SkillLevel.beginner : "advanced" in value ? SkillLevel.advanced : "expert" in value ? SkillLevel.expert : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    movie: null;
} | {
    album: null;
} | {
    other: string;
} | {
    game: null;
} | {
    comic: null;
} | {
    musicVideo: null;
} | {
    shortFilm: null;
} | {
    novel: null;
}): {
    __kind__: "movie";
    movie: null;
} | {
    __kind__: "album";
    album: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "game";
    game: null;
} | {
    __kind__: "comic";
    comic: null;
} | {
    __kind__: "musicVideo";
    musicVideo: null;
} | {
    __kind__: "shortFilm";
    shortFilm: null;
} | {
    __kind__: "novel";
    novel: null;
} {
    return "movie" in value ? {
        __kind__: "movie",
        movie: value.movie
    } : "album" in value ? {
        __kind__: "album",
        album: value.album
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "game" in value ? {
        __kind__: "game",
        game: value.game
    } : "comic" in value ? {
        __kind__: "comic",
        comic: value.comic
    } : "musicVideo" in value ? {
        __kind__: "musicVideo",
        musicVideo: value.musicVideo
    } : "shortFilm" in value ? {
        __kind__: "shortFilm",
        shortFilm: value.shortFilm
    } : "novel" in value ? {
        __kind__: "novel",
        novel: value.novel
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectPosting>): Array<ProjectPosting> {
    return value.map((x)=>from_candid_ProjectPosting_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectRole>): Array<ProjectRole> {
    return value.map((x)=>from_candid_ProjectRole_n20(_uploadFile, _downloadFile, x));
}
function to_candid_CreativeProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreativeProfile): _CreativeProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): _ProjectCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectPosting_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectPosting): _ProjectPosting {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): _ProjectRole {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SkillLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): _SkillLevel {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    createdAt: Time;
    skillTags: Array<string>;
    lookingFor: string;
    availability: string;
    updatedAt: Time;
    moodTags: Array<string>;
    goals: Array<string>;
    genres: Array<string>;
    skillLevel: SkillLevel;
    portfolioLinks: Array<[string, string]>;
    inspirations: Array<string>;
}): {
    bio: string;
    displayName: string;
    createdAt: _Time;
    skillTags: Array<string>;
    lookingFor: string;
    availability: string;
    updatedAt: _Time;
    moodTags: Array<string>;
    goals: Array<string>;
    genres: Array<string>;
    skillLevel: _SkillLevel;
    portfolioLinks: Array<[string, string]>;
    inspirations: Array<string>;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        createdAt: value.createdAt,
        skillTags: value.skillTags,
        lookingFor: value.lookingFor,
        availability: value.availability,
        updatedAt: value.updatedAt,
        moodTags: value.moodTags,
        goals: value.goals,
        genres: value.genres,
        skillLevel: to_candid_SkillLevel_n10(_uploadFile, _downloadFile, value.skillLevel),
        portfolioLinks: value.portfolioLinks,
        inspirations: value.inspirations
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ProjectStatus;
    title: string;
    creator: Principal;
    externalLinks: Array<[string, string]>;
    vibes: Array<string>;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    goals: Array<string>;
    rolesNeeded: Array<ProjectRole>;
    genres: Array<string>;
    category: ProjectCategory;
    timeline: bigint;
}): {
    id: bigint;
    status: _ProjectStatus;
    title: string;
    creator: Principal;
    externalLinks: Array<[string, string]>;
    vibes: Array<string>;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    goals: Array<string>;
    rolesNeeded: Array<_ProjectRole>;
    genres: Array<string>;
    category: _ProjectCategory;
    timeline: bigint;
} {
    return {
        id: value.id,
        status: to_candid_ProjectStatus_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        creator: value.creator,
        externalLinks: value.externalLinks,
        vibes: value.vibes,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        goals: value.goals,
        rolesNeeded: to_candid_vec_n7(_uploadFile, _downloadFile, value.rolesNeeded),
        genres: value.genres,
        category: to_candid_ProjectCategory_n12(_uploadFile, _downloadFile, value.category),
        timeline: value.timeline
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: SkillLevel;
    name: string;
    description: string;
    requiredSkills: Array<string>;
}): {
    experienceLevel: _SkillLevel;
    name: string;
    description: string;
    requiredSkills: Array<string>;
} {
    return {
        experienceLevel: to_candid_SkillLevel_n10(_uploadFile, _downloadFile, value.experienceLevel),
        name: value.name,
        description: value.description,
        requiredSkills: value.requiredSkills
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
} {
    return value == SkillLevel.intermediate ? {
        intermediate: null
    } : value == SkillLevel.beginner ? {
        beginner: null
    } : value == SkillLevel.advanced ? {
        advanced: null
    } : value == SkillLevel.expert ? {
        expert: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "movie";
    movie: null;
} | {
    __kind__: "album";
    album: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "game";
    game: null;
} | {
    __kind__: "comic";
    comic: null;
} | {
    __kind__: "musicVideo";
    musicVideo: null;
} | {
    __kind__: "shortFilm";
    shortFilm: null;
} | {
    __kind__: "novel";
    novel: null;
}): {
    movie: null;
} | {
    album: null;
} | {
    other: string;
} | {
    game: null;
} | {
    comic: null;
} | {
    musicVideo: null;
} | {
    shortFilm: null;
} | {
    novel: null;
} {
    return value.__kind__ === "movie" ? {
        movie: value.movie
    } : value.__kind__ === "album" ? {
        album: value.album
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "game" ? {
        game: value.game
    } : value.__kind__ === "comic" ? {
        comic: value.comic
    } : value.__kind__ === "musicVideo" ? {
        musicVideo: value.musicVideo
    } : value.__kind__ === "shortFilm" ? {
        shortFilm: value.shortFilm
    } : value.__kind__ === "novel" ? {
        novel: value.novel
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == ProjectStatus.cancelled ? {
        cancelled: null
    } : value == ProjectStatus.open ? {
        open: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProjectRole>): Array<_ProjectRole> {
    return value.map((x)=>to_candid_ProjectRole_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
